trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: java -version
    - bash: node --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
#   - job: SecondJob
#     steps:
#     - bash: echo build FirstJob
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#     - job: FirstJob
#       steps:
#       - bash: echo $(environment)Deploy FirstJob
# - stage: Test
#   variables:
#       environment: Test
#   dependsOn: Build
#   jobs:
#     - job: FirstJob
#       steps:
#       - bash: echo $(environment) FirstJob
# - stage: Prod
#   dependsOn: 
#   - DevDeploy
#   - Test
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo Prod FirstJob
