trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azure-demo-docker'
        repository: 'azuredemo/currency-exchange-devops'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'