# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build FirstJob
- stage: DevDeploy
  jobs:
    - job: FirstJob
      steps:
      - bash: echo DevDeploy FirstJob
- stage: Test
  jobs:
    - job: FirstJob
      steps:
      - bash: echo Test FirstJob
- stage: Prod
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Prod FirstJob
